shellEmulator: true

trustPolicy: no-downgrade

ignoredBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - core-js
  - es5-ext
  - esbuild
onlyBuiltDependencies:
  - '@vue-office/docx'
  - '@vue-office/excel'
  - '@vue-office/pdf'
  - vue-demi
